name = "GoogleScholar"
uuid = "cc0898d6-34c9-4540-a58d-8bfbe394b8dc"
authors = ["Robert Moss <rmoss92@gmail.com>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1"
HTTP = "1.1.0, 1.5"
Plots = "1"
